driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-20.04
  - name: centos-7.6
  - name: debian-10

suites:
  - name: default
    run_list:
      - recipe[motd::default]
